FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.2

# Configuration pour environnement à usage personnel
ENV discovery.type=single-node
ENV xpack.security.enabled=false
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"

EXPOSE 9200
